#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Phase 2 -- have the specification certify the checker.

For each witness module the checker mirrors, this emits a TLA+ module that
EXTENDS the *real* module and asserts, as an invariant, the values the checker
computed.  TLC then evaluates those assertions against the specification's own
definitions.  Passing means the specification confirms an independent
implementation; failing means the mirror (or the checker) is wrong -- which is
the point, and is how the AnonymityWitness mirror error was found.

    python3 certify.py            # generate, run TLC, report

Requires: java + tla2tools.jar (TLC_JAR, default ~/tools/tla2tools.jar)
"""

import os
import subprocess
import sys

import leastexit as L

def _find_specs():
    """Locate specs/ by walking up from this file.

    The checker lives in the artifact (anc/checker/) but was developed beside
    the review notes; resolving the path by search rather than by a fixed
    number of "../" means the same file works from either place and cannot
    silently point at a stale copy.
    """
    d = os.path.dirname(os.path.abspath(__file__))
    for _ in range(6):
        cand = os.path.join(d, "specs", "Synthesis.tla")
        if os.path.exists(cand):
            return os.path.dirname(cand)
        cand = os.path.join(d, "anc", "specs", "Synthesis.tla")
        if os.path.exists(cand):
            return os.path.dirname(cand)
        d = os.path.dirname(d)
    raise SystemExit("cannot locate specs/ containing Synthesis.tla")


SPECS = _find_specs()
HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(HERE, "gen")
TLC_JAR = os.environ.get("TLC_JAR", os.path.expanduser("~/tools/tla2tools.jar"))

# Which operators each witness module actually defines.  A certificate may
# only assert over operators the module itself provides -- otherwise we would
# be certifying against our own copy of the definition, which proves nothing.
CAPS = {
    "AuditLogWitness":    {"handles_minus": True,  "ta": False},
    "AnonymityWitness":   {"handles_minus": True,  "ta": False},
    "StrictPriceWitness": {"handles_minus": True,  "ta": False},
    "TAWitness":          {"handles_minus": False, "ta": True},
}

MODELS = {m.__name__: m for m in
          (L.m_auditlog, L.m_anonymity, L.m_strictprice, L.m_ta)}
BY_MODULE = {
    "AuditLogWitness": L.m_auditlog,
    "AnonymityWitness": L.m_anonymity,
    "StrictPriceWitness": L.m_strictprice,
    "TAWitness": L.m_ta,
}


def tla_set(items):
    """Render a Python set of strings as a TLA+ set literal."""
    return "{}" if not items else "{" + ", ".join(
        f'"{i}"' for i in sorted(items)) + "}"


def build_cert(module, model, mutate=False):
    """When `mutate` is set, deliberately state ONE wrong value.

    A certification that only ever passes proves nothing about the checker; it
    could equally be reporting an invariant TLC never evaluates.  `check.sh
    --negative` runs this path and requires TLC to REFUSE it.  The mutation is
    chosen to be semantically wrong but well-typed: the effect's full handle
    set is asserted where the least exit set -- a strict subset for some
    effect in these models, by PriceWithinIntegrity -- belongs.
    """
    caps = CAPS[module]
    ab = L.all_bot(model["E"])
    lines = []
    victim = None
    if mutate:
        for r in sorted(model["E"]):
            if L.handles_minus(model, ab, r) != L.handles(model, r):
                victim = r
                break
        if victim is None:
            raise SystemExit(f"{module}: no strict inclusion to mutate")

    # Global: the closure under the actual labelling.
    lines.append(f"  /\\ Reach = {tla_set(L.reach(model, model['lbl']))}")

    for r in sorted(model["E"]):
        h = L.handles(model, r)
        lines.append(f'  /\\ Handles("{r}") = {tla_set(h)}')
        if caps["handles_minus"]:
            hm = L.handles(model, r) if r == victim \
                else L.handles_minus(model, ab, r)
            lines.append(f'  /\\ HandlesMinus(AllBot, "{r}") = {tla_set(hm)}')

    if caps["ta"]:
        # TAWitness is the one model where total accountability holds.
        lines.append("  /\\ TA")

    body = "\n".join(lines)
    name = module + "Cert"
    return f"""---- MODULE {name} ----
(***************************************************************************)
(* GENERATED by checker/certify.py -- do not edit by hand.                  *)
(*                                                                         *)
(* Every conjunct below is a value computed by the checker, an independent  *)
(* implementation of Proposition 1's procedure.  This module EXTENDS the    *)
(* real witness module, so TLC evaluates each claim against the             *)
(* SPECIFICATION's own definitions of Reach, Handles and HandlesMinus --    *)
(* not against any copy of them.  TLC reporting no error is therefore the   *)
(* specification certifying the tool.                                      *)
(***************************************************************************)
EXTENDS {module}

CheckerOutput ==
{body}

====
"""


CFG = "SPECIFICATION Spec\nINVARIANT CheckerOutput\n"


def run_tlc(name):
    # -metadir per run: TLC names its scratch directory by a whole-second
    # timestamp, and these models finish in under a second, so consecutive
    # runs collide and one of them dies with a stack trace that looks like a
    # verification failure.  It is not one -- but a tool whose failures are
    # indistinguishable from its findings is useless, so give each run its own.
    cmd = ["java", "-XX:+UseParallelGC", "-cp", TLC_JAR, "tlc2.TLC",
           "-metadir", os.path.join("states", name),
           "-config", f"{name}.cfg", f"{name}.tla"]
    p = subprocess.run(cmd, cwd=GEN, capture_output=True, text=True,
                       env={**os.environ, "CLASSPATH": TLC_JAR})
    out = p.stdout + p.stderr
    if "No error has been found" in out:
        return True, "No error has been found."
    # TLC reports a falsified state-predicate invariant as
    #   "Error: The invariant of CheckerOutput is equal to FALSE"
    # not as "... is violated"; matching only the latter silently turns a
    # refutation into "no output", which would make this whole check vacuous.
    for line in out.splitlines():
        if line.startswith("Error") or "is equal to FALSE" in line \
                or "is violated" in line or "is not a module" in line:
            return False, line.strip()
    return False, (out.strip().splitlines()[-1] if out.strip() else "no output")


def negative():
    """Require TLC to reject a deliberately wrong certificate."""
    print("NEGATIVE CONTROL — a wrong value must be refused\n")
    ok_all = True
    for module, factory in BY_MODULE.items():
        if not CAPS[module]["handles_minus"]:
            continue
        model = factory()
        try:
            tla = build_cert(module, model, mutate=True)
        except SystemExit as e:
            print(f"  {module:<22} skipped ({e})")
            continue
        name = module + "Cert"
        with open(os.path.join(GEN, name + ".tla"), "w") as f:
            f.write(tla)
        with open(os.path.join(GEN, name + ".cfg"), "w") as f:
            f.write(CFG)
        accepted, msg = run_tlc(name)
        if accepted:
            ok_all = False
            print(f"  {module:<22} BAD   TLC accepted a wrong value")
        else:
            print(f"  {module:<22} good  TLC refused it: {msg}")
    print()
    if ok_all:
        print("The certification is NOT vacuous: every wrong value was "
              "refused.\nRe-run `python3 certify.py` to restore the true "
              "certificates.")
    else:
        print("VACUOUS — TLC accepted a value the checker knows is wrong. "
              "The invariant\nis not being evaluated; fix that before "
              "believing any PASS above.")
    return 0 if ok_all else 1


def main():
    os.makedirs(GEN, exist_ok=True)
    # TLC resolves EXTENDS from the main file's directory: symlink the real
    # specs in rather than copying, so the certificate can never drift from
    # the module it claims to certify.
    for module in BY_MODULE:
        src, dst = os.path.join(SPECS, module + ".tla"), \
                   os.path.join(GEN, module + ".tla")
        if os.path.islink(dst) or os.path.exists(dst):
            os.remove(dst)
        os.symlink(src, dst)

    # Relative paths only: these logs ship, and an absolute path would put
    # the author's directory layout in the artifact.
    print(f"specs : {os.path.relpath(SPECS, HERE)}")
    print(f"jar   : {os.path.basename(TLC_JAR)}\n")

    results = []
    for module, factory in BY_MODULE.items():
        model = factory()
        name = module + "Cert"
        with open(os.path.join(GEN, name + ".tla"), "w") as f:
            f.write(build_cert(module, model))
        with open(os.path.join(GEN, name + ".cfg"), "w") as f:
            f.write(CFG)
        ok, msg = run_tlc(name)
        results.append(ok)
        print(f"  {name:<26} {'PASS' if ok else 'FAIL'}  {msg}")

    print()
    if all(results):
        print("ALL CERTIFIED — the specification confirms the checker's output "
              "on every witness model.")
    else:
        print("CERTIFICATION FAILED — the checker or a mirror is wrong. "
              "That is a finding, not a nuisance: fix the mirror against the "
              "module, or fix the checker.")
    return 0 if all(results) else 1


def _link_specs():
    os.makedirs(GEN, exist_ok=True)
    for module in BY_MODULE:
        src, dst = os.path.join(SPECS, module + ".tla"), \
                   os.path.join(GEN, module + ".tla")
        if os.path.islink(dst) or os.path.exists(dst):
            os.remove(dst)
        os.symlink(src, dst)


if __name__ == "__main__":
    _link_specs()
    sys.exit(negative() if "--negative" in sys.argv else main())
